[package]
name = "io"
version = "0.1.0"
publish = false
edition = "2018"

[lib]
name = "io"
crate-type = ["staticlib"]

[dependencies]
coro = { path = "../coro" }
crossbeam = "0.7"
gc = { path = "../gc" }
num_cpus = "1"
