[package]
name = "core"
version = "0.1.0"
publish = false
edition = "2018"

[lib]
name = "core"
crate-type = ["staticlib"]

[dependencies]
atty = "0.2"
coro = { path = "../coro" }
gc = { path = "../gc" }
termcolor = "1"
